### ISSUE TITLE
Webkit autofill pseudo selector

### ISSUE THREAD

**Issue by CodingDive** [cerebral/classy-ui#45]
I'm trying to style an `input` field and its default colors when browsers or extensions autofill some values.

```css
/* Change the white to any color ;) */
input:-webkit-autofill,
input:-webkit-autofill:hover, 
input:-webkit-autofill:focus, 
input:-webkit-autofill:active  {
    -webkit-box-shadow: 0 0 0 30px white inset !important;
}
```

https://stackoverflow.com/questions/2781549/removing-input-background-colour-for-chrome-autocomplete

How would I do this in `classy-ui`? Is there a way to extend the [`pseudo decorators`](https://classy-ui.io/api/pseudo-decorators) to apply styles based on autofill (or other selectors)?
